name: Instagram
on:
  workflow_dispatch:
  schedule:
    - cron: "0  0 * * *"
    - cron: "0 12 * * *"

jobs:
  generate_web_feed:
    runs-on: macOS-latest
    name: Generate Web Feed
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Web Feed
        id: web_feed
        uses: ognis1205/instagram-web-feed-action@v1.0.2
        with:
          username: ${{ secrets.INSTAGRAM_USERNAME }}
          password: ${{ secrets.INSTAGRAM_PASSWORD }}
      - name: Commit files
        if: ${{ success() && steps.web_feed.outputs.STATUS == 'success' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add instagram.json
          git commit -am "Updated instagram.json"
          git push -f
